# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/klteduos/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter kltechnduo klteduos,$(TARGET_DEVICE)),)

endif
