# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/ks01ltexx/setup-makefiles.sh

ifeq ($(WITH_TWRP),true)
TARGET_RECOVERY_DEVICE_DIRS += vendor/samsung/ks01ltexx/proprietary
endif
